### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by legendiguess** [GameAnalytics/godot-gameanalytics#1] opened 2021-07-23 04:20 UTC
I get error while trying to install this from NativeLib-UI (immediately after i press install button). Other addons are installing without problem.
<details>
  <summary>Error log</summary>

```
--- Debugging process stopped ---
 modules/gdscript/gdscript_functions.cpp:803 - Command python, exit code 1
Installing gameanalytics@1.3.4
Traceback (most recent call last):
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1417, in connect
    super().connect()
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11003] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\src\insert-shapes\addons\NativeLib\nativelib", line 1172, in <module>
    install_package(p, v)
  File "D:\src\insert-shapes\addons\NativeLib\nativelib", line 946, in install_package
    download_package(package_name, version, package_meta)
  File "D:\src\insert-shapes\addons\NativeLib\nativelib", line 436, in download_package
    path = download(f['url'], fname, home)
  File "D:\src\insert-shapes\addons\NativeLib\nativelib", line 411, in download
    (filepath, headers) = urlretrieve(url, os.path.join(path, filename), reporthook=_progress)
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1385, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\legendiguess\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1345, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11003] getaddrinfo failed>
```

</details>

**Comment by the1schwartz** [comment] 2021-07-26 09:02
Hmmm, I am not able to reproduce this on my end. I am not a Mac though so I don't know if this has anything to do with this? @DrMoriarty do you know what could cause this?

**Comment by DrMoriarty** [comment] 2021-07-26 10:40
@legendiguess Could you install any other plugin from NativeLib? For example `NativeLib Export`

**Comment by legendiguess** [comment] 2021-07-27 10:11
> 
> 
> @legendiguess Could you install any other plugin from NativeLib? For example `NativeLib Export`

I mentioned that before - other plugins from NativeLib installs without a problems(include `NativeLib Export`, `Facebook SDK` and etc).

**Comment by DrMoriarty** [comment] 2021-07-27 10:30
@the1schwartz I fixed an error in NativeLib-CLI which leads to malformed download URLs.
Please, update CLI and republish the plugin.

**Comment by the1schwartz** [comment] 2021-07-27 10:43
Ok thanks @DrMoriarty I will republish plugin now

**Comment by the1schwartz** [comment] 2021-07-27 10:58
Ok I will have updated Native-CLI to 0.5.2 and republished plugin. @legendiguess please let me know if it works now so I know if I can close this issue.

**Comment by legendiguess** [comment] 2021-08-09 09:34
> 
> 
> Ok I will have updated Native-CLI to 0.5.2 and republished plugin. @legendiguess please let me know if it works now so I know if I can close this issue.

Problem was solved after updating the NativeLib

**Comment by the1schwartz** [comment] 2021-08-09 09:47
Ok perfect thanks. I will close the issue then. Thanks for the help @DrMoriarty.

**Closed by the1schwartz** 2021-08-09 09:47 UTC
